### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by GentlemanHal** [ring-clojure/ring-defaults#18]
Although its clear from the README this project is licensed under MIT, I use [Dependency CI](https://dependencyci.com/github/build-canaries/nevergreen/builds/4), which is currently failing as it thinks this project is unlicensed. 

Adding a standard LICENSE file to the project would allow Dependency CI to automatically pick up the correct license.

Thanks 😄

**Comment by weavejester** [comment]
Dependency CI seems to have no issues discovering the license of other Clojure projects without the need for an explicit LICENSE file, including Ring-JSON which is licensed identically. Is there any documentation on what it expects, or how it parses this data? Maybe this is a bug in libraries.io, in which case it won't necessarily be fixed by adding a new file to the repository.

**Comment by GentlemanHal** [comment]
You are correct; I absolutely jumped to the conclusion that it was the missing LICENSE file causing the issue 😔 

Even if it was required, it does seem reasonable for Dependency CI to extract that information from the `project.clj` file. I'll follow up and see if I can raise an issue with them.
