### ISSUE TITLE
Injecting headers into nil responses

### ISSUE THREAD

**Issue by logaan** [ring-clojure/ring-defaults#9]
wrap-defaults will take a nil response (indicating no handler has yet responded) and will return

```clojure
{:headers
 {"X-Content-Type-Options" "nosniff",
  "X-Frame-Options" "SAMEORIGIN",
  "X-XSS-Protection" "1; mode=block"}}
```

This appears to be picked up at some point and turned into a 200 OK. Final response as seen by curl is

```
< HTTP/1.1 200 OK
< X-Content-Type-Options: nosniff
< X-Frame-Options: SAMEORIGIN
< X-Xss-Protection: 1; mode=block
< Content-Length: 0
* Server http-kit is not blacklisted
< Server: http-kit
< Date: Tue, 20 Jan 2015 13:37:02 GMT
<
* Connection #0 to host localhost left intact
```

This is being created from this code
```clojure
      (ring-defaults/wrap-defaults 
        (-> ring-defaults/site-defaults
            (assoc :proxy true)
            (assoc-in [:security :anti-forgery] false)))
```

Desired behaviour is nil in, nil out.

**Comment by theophilusx** [comment]
This issue seems to also affect the compojure route/not-found functionality when you are using the compojure wrap-routes function and applying it to wrap-defaults using the site-defaults config. Have logged it as a separate issue, though I suspect the injection of the headers into the nil response is the root cause.
